name: run tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Download Go modules
        run: go mod download

      - name: Run Go tests
        run: go test ./...
